name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment

    strategy:
      matrix:
        java: ['8']  # Java 8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository code

    - name: Set up JDK 8 (Eclipse Temurin)
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}  # Use Java 8
        distribution: 'temurin'  # Use Eclipse Temurin for Java 8

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Chrome and Chromedriver
      uses: browser-actions/setup-chromium@v1  # Set up Chrome and chromedriver on the runner
      with:
        chromedriver-version: 'latest'  # Specify the version of chromedriver you want (latest is fine)

    - name: Run specific test case defined in the Runner class
      run: mvn clean test -Dtest=Runners.TestRunner  # Specify the Runner class

    - name: Publish Test Results
      if: always()  # Ensure this step runs even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/surefire-reports  # Path where the test reports are stored

    - name: Build with Maven
      run: mvn clean install  # Run Maven build with clean install.
