name: Java CI with Maven

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on the latest Ubuntu environment

    strategy:
      matrix:
        java: [ '8' ]  # You can specify '8' for Java 8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your repository code

    - name: Set up JDK 8
      uses: actions/setup-java@v2  # Set up the JDK version
      with:
        java-version: ${{ matrix.java }}  # Use Java 8

    - name: Build with Maven
      run: mvn clean install  # Run Maven build with clean install
